Repository caicloud/charts, pull requests merged in 2018-04, with the labels that each got.

#42 fix(nodePort): replace blankspace with number for service-nodeport
  stable/filemanager/1.4.4/values.yaml
  stable/galera/5.7.20/values.yaml
  stable/gitlab-ce/10.3.3/values.yaml
  stable/influxdb/1.4.2/values.yaml
  stable/jenkins/2.101.0/values.yaml
  stable/mariadb/10.2.12/values.yaml
  stable/memcached/1.5.4/values.yaml
  stable/mongo/3.6.1/values.yaml
  stable/mysql/5.7.20/values.yaml
  stable/nginx/1.13.8/values.yaml
  stable/rabbitmq/3.7.2/values.yaml
  stable/redmine/3.4.4/values.yaml
  stable/wordpress/4.9.1/values.yaml
Labels: caicloud-cla: yes, lgtm, release-note-none, size/M

#43 fix(template): fix template issues of cronjob and schedule
  templates/1.0.0/templates/_scheduler.tpl
  templates/1.0.0/templates/cronjobs.yaml
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/M

#44 fix(template): correct daemonset updateStrategy
  templates/1.0.0/templates/daemonsets.yaml
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/XS

#45 feat(template): add quote for all string fields
  templates/1.0.0/templates/_pod.tpl
  templates/1.0.0/templates/_scheduler.tpl
  templates/1.0.0/templates/_volumes.tpl
  templates/1.0.0/templates/cronjobs.yaml
  templates/1.0.0/templates/daemonsets.yaml
  templates/1.0.0/templates/deployments.yaml
  templates/1.0.0/templates/jobs.yaml
  templates/1.0.0/templates/statefulsets.yaml
  templates/1.0.0/templates/volumes.yaml
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/L

#46 feat(*): add configs and secrets
  README.md
  templates/1.0.0/templates/_volumes.tpl
  templates/1.0.0/templates/configmaps.yaml
  templates/1.0.0/templates/secrets.yaml
  templates/1.0.0/values.yaml
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/L

#47 feat(k8s): update kubernetes api to 1.10
  .gitignore
  templates/1.0.0/templates/cronjobs.yaml
  templates/1.0.0/templates/daemonsets.yaml
  templates/1.0.0/templates/deployments.yaml
  templates/1.0.0/templates/statefulsets.yaml
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/XS

#48 feat: add templates image
  Makefile
  build/charts/test.sh
  build/templates/Dockerfile
  build/templates/build.sh
  build/templates/test.sh
Labels: approved, caicloud-cla: yes, lgtm, release-note, size/L

#49 fix: selector must match labels in template
  templates/1.0.0/templates/_labels.tpl
  templates/1.0.0/templates/configmaps.yaml
  templates/1.0.0/templates/cronjobs.yaml
  templates/1.0.0/templates/daemonsets.yaml
  templates/1.0.0/templates/deployments.yaml
  templates/1.0.0/templates/jobs.yaml
  templates/1.0.0/templates/secrets.yaml
  templates/1.0.0/templates/services.yaml
  templates/1.0.0/templates/statefulsets.yaml
  templates/1.0.0/templates/volumes.yaml
Labels: approved, caicloud-cla: yes, lgtm, release-note, size/M
