Repository caicloud/charts, pull requests merged in 2018-12, with the labels that each got.

#130 feat(microservice): change the default access type
  stable/config-server/2.0.0/values.yaml
  stable/eureka/2.0.0/values.yaml
  stable/hystrix-dashboard/1.2.3/values.yaml
  stable/turbine/2.0.0/values.yaml
  stable/zipkin/2.11.8/values.yaml
  stable/zuul/2.0.0/values.yaml
Labels: approved, caicloud-cla: yes, lgtm, release-note, size/M

#132 feat: support Recreate strategy in deployment
  Makefile
  README.md
  stable/rabbitmq/3.7.2/values.yaml
  templates/1.0.0/templates/deployments.yaml
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/S

#139 fix(statefulset): fix statefulset pod template labels
  Makefile
  templates/1.0.0/templates/statefulsets.yaml
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/XS

#141 fix(mount): transform mount type from Scratch to Static
  stable/filemanager/1.4.4/values.yaml
  stable/gitlab-ce/10.3.3/values.yaml
  stable/influxdb/1.4.2/values.yaml
  stable/jenkins/2.101.0/values.yaml
  stable/mariadb/10.2.12/values.yaml
  stable/mongo/3.6.1/values.yaml
  stable/mysql/5.7.20/values.yaml
  stable/redis/4.0.6/values.yaml
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/S

#143 chore(version): update version
  Makefile
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/XS
