Repository caicloud/charts, pull requests merged in 2018-10, with the labels that each got.

#97 docs(*): fix HTTP probe handler description
  README.md
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/XS

#99 fix(stateful): fix statefulset podManagementPolicy
  README.md
  templates/1.0.0/templates/statefulsets.yaml
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/S

#101 chore(docs): update VERSION to v1.2.13
  Makefile
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/XS

#103 Revert "fix(statefulset): add statefulset service default port (#83)"
  templates/1.0.0/templates/statefulsets.yaml
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/XS

#104 fix(microservice): modify hystrix-dashboard image
  stable/hystrix-dashboard/1.5.12/description.yaml
  stable/hystrix-dashboard/1.5.12/values.yaml
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/S

#106 fix(zipkin): modify zipkin request quota & service port
  stable/zipkin/2.9.3/description.yaml
  stable/zipkin/2.9.3/values.yaml
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/S

#108 fix(eureka): modify eureka request quota
  stable/eureka/1.9.2/description.yaml
  stable/eureka/1.9.2/values.yaml
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/XS

#112 feat: delete service export
  README.md
  stable/filemanager/1.4.4/values.yaml
  stable/galera/5.7.20/values.yaml
  stable/gitlab-ce/10.3.3/values.yaml
  stable/influxdb/1.4.2/values.yaml
  stable/jenkins/2.101.0/values.yaml
  stable/mariadb/10.2.12/values.yaml
  stable/memcached/1.5.4/values.yaml
  stable/mongo/3.6.1/values.yaml
  stable/mysql/5.7.20/values.yaml
  stable/nginx/1.13.8/values.yaml
  stable/rabbitmq/3.7.2/values.yaml
  stable/redmine/3.4.4/values.yaml
  stable/wordpress/4.9.1/values.yaml
  templates/1.0.0/templates/services.yaml
  templates/1.0.0/templates/statefulsets.yaml
  templates/1.0.0/values.yaml
Labels: approved, caicloud-cla: yes, lgtm, size/S

#116 fix(stable): modify the charts so that they matche the description
  stable/filemanager/1.4.4/values.yaml
  stable/galera/5.7.20/values.yaml
  stable/gitlab-ce/10.3.3/values.yaml
  stable/influxdb/1.4.2/values.yaml
  stable/jenkins/2.101.0/values.yaml
  stable/mariadb/10.2.12/values.yaml
  stable/memcached/1.5.4/values.yaml
  stable/mongo/3.6.1/values.yaml
  stable/mysql/5.7.20/values.yaml
  stable/nginx/1.13.8/values.yaml
  stable/rabbitmq/3.7.2/values.yaml
  stable/redis/4.0.6/description.yaml
  stable/redis/4.0.6/values.yaml
  stable/redmine/3.4.4/values.yaml
  stable/wordpress/4.9.1/values.yaml
Labels: approved, caicloud-cla: yes, lgtm, release-note, size/M
