Repository caicloud/charts, pull requests merged in 2018-09, with the labels that each got.

#67 feat(tmpl): support glusterfs
  README.md
  templates/1.0.0/templates/_volumes.tpl
Labels: caicloud-cla: yes, release-note-none, size/S

#69 chore(docs): update VERSION to v1.2.8
  Makefile
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/XS

#75 chore(*): modify OWNERS & CODEOWNERS
  CODEOWNERS
  OWNERS
Labels: caicloud-cla: yes, release-note-none, size/XS

#74 docs(*): update README.md
  README.md
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/M

#72 fix(hostAliases): add hostAliases for pod template
  templates/1.0.0/templates/_pod.tpl
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/S

#71 fix(statefulset): support OnDelete updsateStrateg for statefulset
  templates/1.0.0/templates/statefulsets.yaml
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/XS

#73 fix(runAsNonRoot): add runAsNonRoot for pod template
  templates/1.0.0/templates/_pod.tpl
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/XS

#81 chore(docs): update VERSION to v1.2.9
  Makefile
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/XS

#83 fix(statefulset): add statefulset service default port
  templates/1.0.0/templates/statefulsets.yaml
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/XS

#85 chore(docs): update VERSION to v1.2.10
  Makefile
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/XS

#87 feat(microservice): add eureka, hystrix-dashboard and zipkin
  stable/eureka/1.9.2/Chart.yaml
  stable/eureka/1.9.2/description.yaml
  stable/eureka/1.9.2/values.yaml
  stable/hystrix-dashboard/1.5.12/Chart.yaml
  stable/hystrix-dashboard/1.5.12/description.yaml
  stable/hystrix-dashboard/1.5.12/values.yaml
  stable/zipkin/2.9.3/Chart.yaml
  stable/zipkin/2.9.3/description.yaml
  stable/zipkin/2.9.3/values.yaml
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/L

#89 chore(docs): update VERSION to v1.2.11
  Makefile
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/XS

#91 fix(filemanager): fix filemanager image
  stable/filemanager/1.4.4/values.yaml
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/XS

#92 fix(statefulset): fix mysql & rabbitmq config
  stable/mysql/5.7.20/values.yaml
  stable/rabbitmq/3.7.2/values.yaml
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/XS

#95 chore(docs): update VERSION to v1.2.12
  Makefile
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/XS
