Repository caicloud/charts, pull requests merged in 2019-07, with the labels that each got.

#173 feat(service): custom selector for service
  templates/1.0.0/templates/services.yaml
Labels: approved, caicloud-cla: yes, do-not-merge/hold, lgtm, release-note-none, size/S

#175 fix(script): update build script
  build/charts/build.sh
  build/charts/test.sh
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/S

#177 adapt compass 2.8.x
  templates/1.0.0/templates/_scheduler.tpl
  templates/1.0.0/templates/services.yaml
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/S

#179 [CPS-2423] fix(release): add es initcontainer resource
  build/charts/Dockerfile
  build/charts/build.sh
  stable/release/elasticsearch/6.5.4/values.yaml
  stable/release/kibana/6.5.4/values.yaml
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/S

#181 feat(wanda): add dns config into pod's template
  README.md
  templates/1.0.0/templates/_pod.tpl
  templates/1.0.0/values.yaml
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/S

#178 feat(sessionAffinity): add service session affinity
  README.md
  templates/1.0.0/templates/services.yaml
  templates/1.0.0/values.yaml
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/S

#183 [CPS-2559] fix(type): add daemonset updateStrategy type
  templates/1.0.0/templates/daemonsets.yaml
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/XS

#185 [CPS-2596]fix(service): config service nodeport to clusterip
  Makefile
  stable/application/BookInfo/0.0.1/config.json
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/XS

#187 fix(version): modify es image version
  stable/release/elasticsearch/6.5.4/values.yaml
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/XS

#189 fix(image): correct images
  stable/release/elasticsearch/6.5.4/values.yaml
  stable/release/kibana/6.5.4/values.yaml
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/XS
