Repository caicloud/charts, pull requests merged in 2019-08, with the labels that each got.

#191 [CPS-2423] fix(volume): es uses dedicated type volume
  Makefile
  stable/release/elasticsearch/6.5.4/values.yaml
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/XS

#193 chore(README): update readme
  README.md
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/XS

#196 chore(owner): update owners
  OWNERS
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/XS

#195 feat(wanda): cherry-pick to v1.3.2
  Makefile
  README.md
  templates/1.0.0/templates/_helpers.tpl
  templates/1.0.0/templates/_labels.tpl
  templates/1.0.0/templates/_pod.tpl
  templates/1.0.0/templates/_scheduler.tpl
  templates/1.0.0/templates/configmaps.yaml
  templates/1.0.0/templates/cronjobs.yaml
  templates/1.0.0/templates/daemonsets.yaml
  templates/1.0.0/templates/deployments.yaml
  templates/1.0.0/templates/jobs.yaml
  templates/1.0.0/templates/secrets.yaml
  templates/1.0.0/templates/services.yaml
  templates/1.0.0/templates/statefulsets.yaml
  templates/1.0.0/templates/volumes.yaml
  templates/1.0.0/values.yaml
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/L

#197 [CPS-3429]chore(*): remove useless Jenkinsfile
  Jenkinsfile
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/M
