Repository caicloud/charts, pull requests merged in 2020-12, with the labels that each got.

#242 [guosen]chore(*): rebase v1.4.5
  Makefile
  README.md
  build/charts/Dockerfile
  templates/1.0.0/templates/cronjobs.yaml
  templates/1.0.0/templates/jobs.yaml
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/M

#244 feat(guosen): support runAsUser & runAsGroup
  README.md
  templates/1.0.0/templates/_pod.tpl
  templates/1.0.0/values.yaml
Labels: approved, caicloud-cla: yes, kind/feature, lgtm, release-note-none, size/S

#245 [BEST-39] use controller name label to match canary deployments
  templates/1.0.0/templates/deployments.yaml
  templates/1.0.0/templates/services.yaml
Labels: approved, area/apps, caicloud-cla: yes, kind/feature, lgtm, release-note-none, size/S
