Repository caicloud/charts, pull requests merged in 2020-06, with the labels that each got.

#219 [BEST-73]remove default service selector
  templates/1.0.0/templates/services.yaml
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/XS

#222 [CPS-7403] chore(*): use base image to build
  Makefile
  build/charts/Dockerfile
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/S

#223 chore(*): use base image debian:stretch-ruby (#222)
  Makefile
  build/charts/Dockerfile
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/S

#221 [CPS-7378] feat: add backoffLimit for job and cronjob
  Makefile
  README.md
  templates/1.0.0/templates/cronjobs.yaml
  templates/1.0.0/templates/jobs.yaml
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/M
